default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: Gopi@4674
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: vuerailsdemo_development

test:
  <<: *default
  database: vuerailsdemo_test

production:
  DATABASE_URL="mysql2://myuser:mypass@localhost/vuerailsdemo"
  url: <%= ENV['DATABASE_URL'] %>
